// <auto-generated />
using System;
using System.Collections;
using AutoSalon.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoSalon.Migrations
{
    [DbContext(typeof(AutoSalonContext))]
    [Migration("20260401184949_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoSalon.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<char>("Gendercode")
                        .HasColumnType("character(1)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Photopath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("Registrationtime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Gendercode");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("AutoSalon.Entities.Gender", b =>
                {
                    b.Property<char>("Code")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Code");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("AutoSalon.Entities.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("Startdate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("AutoSalon.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("money");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<BitArray>("Isactive")
                        .IsRequired()
                        .HasColumnType("bit(1)");

                    b.Property<string>("Mainimage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Manufacturerid")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Manufacturerid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AutoSalon.Entities.Productphoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Photopath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Productid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Productid");

                    b.ToTable("Productphotos");
                });

            modelBuilder.Entity("AutoSalon.Entities.Productsale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Clientid")
                        .HasColumnType("integer");

                    b.Property<int>("Productid")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Saledate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Clientid");

                    b.HasIndex("Productid");

                    b.ToTable("Productsales");
                });

            modelBuilder.Entity("AutoSalon.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AutoSalon.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Roleid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Roleid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AutoSalon.Entities.Client", b =>
                {
                    b.HasOne("AutoSalon.Entities.Gender", "GendercodeNavigation")
                        .WithMany("Clients")
                        .HasForeignKey("Gendercode")
                        .IsRequired();

                    b.Navigation("GendercodeNavigation");
                });

            modelBuilder.Entity("AutoSalon.Entities.Product", b =>
                {
                    b.HasOne("AutoSalon.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("Manufacturerid");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("AutoSalon.Entities.Productphoto", b =>
                {
                    b.HasOne("AutoSalon.Entities.Product", "Product")
                        .WithMany("Productphotos")
                        .HasForeignKey("Productid")
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AutoSalon.Entities.Productsale", b =>
                {
                    b.HasOne("AutoSalon.Entities.Client", "Client")
                        .WithMany("Productsales")
                        .HasForeignKey("Clientid")
                        .IsRequired();

                    b.HasOne("AutoSalon.Entities.Product", "Product")
                        .WithMany("Productsales")
                        .HasForeignKey("Productid")
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AutoSalon.Entities.User", b =>
                {
                    b.HasOne("AutoSalon.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("Roleid")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AutoSalon.Entities.Client", b =>
                {
                    b.Navigation("Productsales");
                });

            modelBuilder.Entity("AutoSalon.Entities.Gender", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("AutoSalon.Entities.Manufacturer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AutoSalon.Entities.Product", b =>
                {
                    b.Navigation("Productphotos");

                    b.Navigation("Productsales");
                });

            modelBuilder.Entity("AutoSalon.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
